name: Publish site
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "app/**"
      - ".github/workflows/main.yaml"

env:
  API_URL: https://api.app.davidvargas.me
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  CLERK_FRONTEND_API: clerk.davidvargas.me
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
  CONVERTKIT_API_KEY: ${{ secrets.CONVERTKIT_API_KEY }}
  CONVERTKIT_FORM_ID: 3367475
  DATABASE_URL: mysql://app:${{ secrets.MYSQL_PASSWORD }}@vargas-arts.c2sjnb5f4d57.us-east-1.rds.amazonaws.com:5432/app
  INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
  IS_PRODUCTION: 1
  ORIGIN: https://app.davidvargas.me
  STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npm run build -- --readable
      - name: deploy
        run: npm run deploy
