name: Publish package
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "app/package/**"
      - "prepare.js"
      - ".github/workflows/package.yaml"
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: install
        run: npm install
      - name: patch
        run: node patch.js
      - name: build
        run: npx tsc -p tsconfig.json --noEmit false
      - name: prepare
        run: node prepare.js
      - name: write
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - name: publish
        run: npm publish --access public
        working-directory: dist
